[package]
name = "facilities"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "books",
    "http-client",
    "http-server", "one-zero-four-client",
    "os-checker", "server",
    "test-json", "test-warp",
    "websocket",
]

[dependencies]