[package]
name = "http-client"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "downloader"



[dependencies]
reqwest = { version = "0.11", features = ["json", "stream", "socks"] }
tokio = { version = "1", features = ["full"] }
indicatif = "0.17"
futures-util = "0.3"
