[package]
name = "websocket"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"

[[bin]]
name = "client"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = "0.18"
futures-util = "0.3"
url = "2.2"